"""Print one clear PASS or FAIL line per check, and exit with an error if any check failed.

On GitHub Actions each problem is also sent as an ::error annotation. Under act or when
run by hand, problems are printed as plain indented lines instead.

Notice: This script was generated by AI.
"""
import os
import sys

ANNOTATE = os.environ.get("GITHUB_ACTIONS") == "true" and not os.environ.get("ACT")
COLOR = not os.environ.get("NO_COLOR")
GREEN, RED, RESET = ("\033[32m", "\033[31m", "\033[0m") if COLOR else ("", "", "")

_failed = []


def check(name, problems, file="data.csv"):
    """Report one check. problems is a list of messages; an empty list means it passed."""
    if not problems:
        print(f"{GREEN}✅ PASS{RESET}  {name}")
        return
    _failed.append(name)
    count = f"{len(problems)} problem" + ("s" if len(problems) != 1 else "")
    print(f"{RED}❌ FAIL{RESET}  {name} ({count})")
    for problem in problems:
        if ANNOTATE:
            print(f"::error file={file}::{problem}")
        else:
            print(f"         {problem}")


def finish():
    """Exit with status 1 if any check failed."""
    sys.exit(1 if _failed else 0)
