"""Check that datapackage.json matches data.csv and the column tables in both READMEs.

The fields in datapackage.json and the columns in README.md and README.ja.md must be the
CSV columns in the same order. Each field's description and example must be exactly the
ones in README.md, and the examples in both READMEs must be poem 60's values.

Notice: This script was generated by AI.
"""
import csv
import json
import re

from _report import check, finish

EXAMPLE_POEM = "60"
READMES = ("README.md", "README.ja.md")
COLUMN_ROW = re.compile(r"^\|`([a-z_0-9]+)`\|(.*)\|`(.*)`\|$", re.M)

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    example_row = next(r for r in reader if r["number"] == EXAMPLE_POEM)

with open("datapackage.json", encoding="utf-8") as f:
    package = json.load(f)

readmes = {}
for name in READMES:
    with open(name, encoding="utf-8") as f:
        readmes[name] = {
            m.group(1): (m.group(2).replace("\\|", "|"), m.group(3).replace("\\|", "|"))
            for m in COLUMN_ROW.finditer(f.read())
        }


def compare_columns(columns):
    """Describe how columns differ from the CSV header, as a list of problems."""
    missing = [c for c in header if c not in columns]
    extra = [c for c in columns if c not in header]
    problems = ([f"missing {missing}"] if missing else []) + ([f"extra {extra}"] if extra else [])
    if problems:
        return problems
    for i, (a, b) in enumerate(zip(columns, header)):
        if a != b:
            return [f"column {i + 1} is {a}, but the CSV header has {b}"]
    return []


resources = [r for r in package.get("resources", []) if r.get("path") == "data.csv"]
check(
    "datapackage.json has one resource for data.csv",
    [] if len(resources) == 1 else [f"found {len(resources)} resources with path data.csv"],
    file="datapackage.json",
)
fields = resources[0].get("schema", {}).get("fields", []) if len(resources) == 1 else []

check("datapackage.json fields match the data.csv columns", compare_columns([f.get("name") for f in fields]), file="datapackage.json")
for name, table in readmes.items():
    check(f"{name} columns match the data.csv columns", compare_columns(list(table)), file=name)
    check(
        f"{name} examples are poem {EXAMPLE_POEM}'s values",
        [
            f"example of {column} is {example!r}, but poem {EXAMPLE_POEM} has {example_row[column]!r}"
            for column, (_, example) in table.items()
            if column in example_row and example != example_row[column]
        ],
        file=name,
    )

english = readmes["README.md"]
check(
    "datapackage.json descriptions match README.md",
    [
        f"description of {f['name']} differs from README.md"
        for f in fields
        if f.get("name") in english and f.get("description") != english[f["name"]][0]
    ],
    file="datapackage.json",
)
check(
    "datapackage.json examples match README.md",
    [
        f"example of {f['name']} is {f.get('example')!r}, README.md has {english[f['name']][1]!r}"
        for f in fields
        if f.get("name") in english and str(f.get("example")) != english[f["name"]][1]
    ],
    file="datapackage.json",
)
finish()
