"""Check every cell of data.csv against the schema in datapackage.json, using Frictionless.

Needs the frictionless package: pip install frictionless

Notice: This script was generated by AI.
"""
from frictionless import validate

from _report import check, finish

def describe(error):
    """Prefix an error message with its row and field, when it has them."""
    where = [f"row {error.row_number}"] if getattr(error, "row_number", None) else []
    where += [error.field_name] if getattr(error, "field_name", None) else []
    return f"{', '.join(where)}: {error.message}" if where else error.message


result = validate("datapackage.json")
problems = [describe(e) for e in result.errors] + [describe(e) for task in result.tasks for e in task.errors]
check("data.csv matches the datapackage.json schema (types, required cells, allowed values)", problems)
finish()
