"""Check that each number 1-100 and 序歌 appear once and each color_num 1-20 appears exactly 5 times.

Notice: This script was generated by AI.
"""
import csv
from collections import Counter

from _report import check, finish

JOKA = "序歌"

with open("data.csv", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

number_problems = []
numbers = Counter(r["number"] for r in rows)
for n, count in numbers.items():
    if count > 1:
        number_problems.append(f"number {n} appears {count} times")
expected = {str(i) for i in range(1, 101)}
for n in sorted(expected - numbers.keys(), key=int):
    number_problems.append(f"number {n} is missing")
if JOKA not in numbers:
    number_problems.append(f"number {JOKA} is missing")
for n in sorted(numbers.keys() - expected - {JOKA}):
    number_problems.append(f"number {n!r} is out of range 1-100")
check(f"numbers 1-100 and {JOKA} appear exactly once", number_problems)

rows = [r for r in rows if r["number"] != JOKA]

color_num_problems = []
color_nums = Counter(r["color_num"] for r in rows)
for n in (str(i) for i in range(1, 21)):
    if color_nums[n] != 5:
        color_num_problems.append(f"color_num {n} appears {color_nums[n]} times, expected 5")
for n in sorted(color_nums.keys() - {str(i) for i in range(1, 21)}):
    color_num_problems.append(f"color_num {n!r} is out of range 1-20")
check("color_num 1-20 each appear exactly 5 times", color_num_problems)

colors = Counter((r["color"], r["color_num"]) for r in rows)
check(
    "no color and color_num pair repeats",
    [f"color {color} {num} appears {count} times" for (color, num), count in colors.items() if count > 1],
)
finish()
