"""Check that every row has all columns and no empty fields.

The 序歌 row has no card, so its color, kimariji and torifuda columns must be empty.

Notice: This script was generated by AI.
"""
import csv

from _report import check, finish

JOKA = "序歌"
NO_CARD_PREFIXES = ("color", "kimariji_", "torifuda_")

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    rows = list(reader)

wrong_length, empty, joka_filled = [], [], []

for line, row in enumerate(rows, start=2):
    if None in row or len(row) != len(header):
        wrong_length.append(f"line {line}: expected {len(header)} columns")
    for col, val in row.items():
        if col is None:
            continue
        is_empty = not (val or "").strip()
        if row["number"] == JOKA and col.startswith(NO_CARD_PREFIXES):
            if not is_empty:
                joka_filled.append(f"line {line}: {JOKA} has no card, so {col} must be empty")
        elif is_empty:
            empty.append(f"line {line}: empty {col}")

check(f"all {len(rows)} rows have {len(header)} columns", wrong_length)
check("no empty cells", empty)
check(f"{JOKA} card columns are empty", joka_filled)
finish()
