"""Check that datapackage.json matches data.csv and the column tables in both READMEs.

The fields in datapackage.json and the columns in README.md and README.ja.md must be the
CSV columns in the same order. Each field's description and example must be exactly the
ones in README.md, and the examples in both READMEs must be poem 60's values.

Notice: This script was generated by AI.
"""
import csv
import json
import re
import sys

EXAMPLE_POEM = "60"
READMES = ("README.md", "README.ja.md")
COLUMN_ROW = re.compile(r"^\|`([a-z_0-9]+)`\|(.*)\|`(.*)`\|$", re.M)

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    example_row = next(r for r in reader if r["number"] == EXAMPLE_POEM)

with open("datapackage.json", encoding="utf-8") as f:
    package = json.load(f)

readmes = {}
for name in READMES:
    with open(name, encoding="utf-8") as f:
        readmes[name] = {
            m.group(1): (m.group(2).replace("\\|", "|"), m.group(3).replace("\\|", "|"))
            for m in COLUMN_ROW.finditer(f.read())
        }

errors = []


def compare_columns(columns):
    """Describe how columns differ from the CSV header, or return None if they match."""
    missing = [c for c in header if c not in columns]
    extra = [c for c in columns if c not in header]
    parts = ([f"missing {missing}"] if missing else []) + ([f"extra {extra}"] if extra else [])
    if parts:
        return "columns: " + ", ".join(parts)
    for i, (a, b) in enumerate(zip(columns, header)):
        if a != b:
            return f"columns: column {i + 1} is {a}, but the CSV header has {b}"
    return None


resources = [r for r in package.get("resources", []) if r.get("path") == "data.csv"]
if len(resources) != 1:
    errors.append(("datapackage.json", "expected exactly one resource with path data.csv"))
    fields = []
else:
    fields = resources[0].get("schema", {}).get("fields", [])

for file, columns in [("datapackage.json", [f.get("name") for f in fields])] + [
    (name, list(table)) for name, table in readmes.items()
]:
    problem = compare_columns(columns)
    if problem:
        errors.append((file, problem))

for name, table in readmes.items():
    for column, (_, example) in table.items():
        if column in example_row and example != example_row[column]:
            errors.append((name, f"example of {column} is {example!r}, but poem {EXAMPLE_POEM} has {example_row[column]!r}"))

english = readmes["README.md"]
for field in fields:
    name = field.get("name")
    if name not in english:
        continue
    description, example = english[name]
    if field.get("description") != description:
        errors.append(("datapackage.json", f"description of {name} differs from README.md"))
    if str(field.get("example")) != example:
        errors.append(("datapackage.json", f"example of {name} is {field.get('example')!r}, README.md has {example!r}"))

for file, e in errors:
    print(f"::error file={file}::{file}: {e}")
if errors:
    sys.exit(1)
print(f"OK: {len(fields)} fields match data.csv, README.md and README.ja.md")
