"""Check that datapackage.json matches data.csv and the column table in README.md.

The fields must be the CSV columns in the same order, and each field's description and
example must be exactly the ones in the README table. The examples must be poem 60's values.

Notice: This script was generated by AI.
"""
import csv
import json
import re
import sys

EXAMPLE_POEM = "60"

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    example_row = next(r for r in reader if r["number"] == EXAMPLE_POEM)

with open("datapackage.json", encoding="utf-8") as f:
    package = json.load(f)

with open("README.md", encoding="utf-8") as f:
    readme = {
        m.group(1): (m.group(2).replace("\\|", "|"), m.group(3).replace("\\|", "|"))
        for m in re.finditer(r"^\|`([a-z_0-9]+)`\|(.*)\|`(.*)`\|$", f.read(), re.M)
    }

errors = []


def compare_columns(columns, what):
    """Describe how columns differ from the CSV header, or return None if they match."""
    missing = [c for c in header if c not in columns]
    extra = [c for c in columns if c not in header]
    parts = ([f"missing {missing}"] if missing else []) + ([f"extra {extra}"] if extra else [])
    if parts:
        return f"{what}: " + ", ".join(parts)
    for i, (a, b) in enumerate(zip(columns, header)):
        if a != b:
            return f"{what}: column {i + 1} is {a}, but the CSV header has {b}"
    return None


resources = [r for r in package.get("resources", []) if r.get("path") == "data.csv"]
if len(resources) != 1:
    errors.append(("datapackage.json", "expected exactly one resource with path data.csv"))
    fields = []
else:
    fields = resources[0].get("schema", {}).get("fields", [])

for file, columns in (("datapackage.json", [f.get("name") for f in fields]), ("README.md", list(readme))):
    problem = compare_columns(columns, "columns")
    if problem:
        errors.append((file, problem))

for field in fields:
    name = field.get("name")
    if name not in readme:
        continue
    description, example = readme[name]
    if field.get("description") != description:
        errors.append(("datapackage.json", f"description of {name} differs from README.md"))
    if str(field.get("example")) != example:
        errors.append(("datapackage.json", f"example of {name} is {field.get('example')!r}, README.md has {example!r}"))
    if name in example_row and example != example_row[name]:
        errors.append(("README.md", f"example of {name} is {example!r}, but poem {EXAMPLE_POEM} has {example_row[name]!r}"))

for file, e in errors:
    print(f"::error file={file}::{file}: {e}")
if errors:
    sys.exit(1)
print(f"OK: {len(fields)} fields match data.csv and README.md")
