"""Check that each number 1-100 appears once and each color_num 1-20 appears exactly 5 times.

Notice: This script was generated by AI.
"""
import csv
import sys
from collections import Counter

with open("data.csv", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

errors = []

numbers = Counter(r["number"] for r in rows)
for n, count in numbers.items():
    if count > 1:
        errors.append(f"number {n} appears {count} times")
expected = {str(i) for i in range(1, 101)}
for n in sorted(expected - numbers.keys(), key=int):
    errors.append(f"number {n} is missing")
for n in sorted(numbers.keys() - expected):
    errors.append(f"number {n!r} is out of range 1-100")

color_nums = Counter(r["color_num"] for r in rows)
for n in (str(i) for i in range(1, 21)):
    if color_nums[n] != 5:
        errors.append(f"color_num {n} appears {color_nums[n]} times, expected 5")
for n in sorted(color_nums.keys() - {str(i) for i in range(1, 21)}):
    errors.append(f"color_num {n!r} is out of range 1-20")

colors = Counter((r["color"], r["color_num"]) for r in rows)
for (color, num), count in colors.items():
    if count > 1:
        errors.append(f"color {color} {num} appears {count} times")

for e in errors:
    print(f"::error file=data.csv::{e}")
if errors:
    sys.exit(1)
print("OK: numbers 1-100 once each, color_num 1-20 five times each")
