"""Check that every row has all columns and no empty fields.

The 序歌 row has no card, so its color, kimariji and torifuda columns must be empty.

Notice: This script was generated by AI.
"""
import csv
import sys

JOKA = "序歌"
NO_CARD_PREFIXES = ("color", "kimariji_", "torifuda_")

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    rows = list(reader)

errors = []

for line, row in enumerate(rows, start=2):
    if None in row or len(row) != len(header):
        errors.append(f"line {line}: expected {len(header)} columns")
    for col, val in row.items():
        if col is None:
            continue
        empty = not (val or "").strip()
        if row["number"] == JOKA and col.startswith(NO_CARD_PREFIXES):
            if not empty:
                errors.append(f"line {line}: {JOKA} has no card, so {col} must be empty")
        elif empty:
            errors.append(f"line {line}: empty {col}")

for e in errors:
    print(f"::error file=data.csv::{e}")
if errors:
    sys.exit(1)
print(f"OK: {len(rows)} rows")
