"""Check that every row has all columns and no empty fields.

Notice: This script was generated by AI.
"""
import csv
import sys

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    rows = list(reader)

errors = []

for line, row in enumerate(rows, start=2):
    if None in row or len(row) != len(header):
        errors.append(f"line {line}: expected {len(header)} columns")
    for col, val in row.items():
        if col is not None and not (val or "").strip():
            errors.append(f"line {line}: empty {col}")

for e in errors:
    print(f"::error file=data.csv::{e}")
if errors:
    sys.exit(1)
print(f"OK: {len(rows)} rows")
