"""Check the [kanji|reading] ruby columns against their _kanji and _hiragana columns.

For every column X that has both X_kanji and X_hiragana, X must be well-formed and
resolve to X_kanji when each [A|B] is replaced by A, and to X_hiragana when replaced by B.

Notice: This script was generated by AI.
"""
import csv
import re
import sys

GROUP = re.compile(r"\[([^\[\]|]+)\|([^\[\]|]+)\]")

with open("data.csv", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    rows = list(reader)

columns = [c for c in header if f"{c}_kanji" in header and f"{c}_hiragana" in header]
errors = []

for line, row in enumerate(rows, start=2):
    for col in columns:
        value = row[col]
        where = f"line {line} (number {row['number']}) {col}"
        if any(ch in GROUP.sub("", value) for ch in "[]|"):
            errors.append(f"{where}: malformed ruby {value!r}")
            continue
        base = GROUP.sub(r"\1", value)
        reading = GROUP.sub(r"\2", value)
        if base != row[f"{col}_kanji"]:
            errors.append(f"{where}: resolves to {base!r}, but {col}_kanji is {row[f'{col}_kanji']!r}")
        if reading != row[f"{col}_hiragana"]:
            errors.append(f"{where}: reads as {reading!r}, but {col}_hiragana is {row[f'{col}_hiragana']!r}")

for e in errors:
    print(f"::error file=data.csv::{e}")
if errors:
    sys.exit(1)
print(f"OK: {len(columns)} ruby columns in {len(rows)} rows ({', '.join(columns)})")
